
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Jul 27 13:37:45 CST 2023
//----------------------------------------------------

package codigo;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Op_relacional = 24;
  public static final int SP = 42;
  public static final int Llave_c = 31;
  public static final int Op_booleano = 27;
  public static final int Llave_a = 30;
  public static final int If = 9;
  public static final int Void = 17;
  public static final int Clase = 15;
  public static final int Else = 10;
  public static final int Corchete_c = 33;
  public static final int Corchete_a = 32;
  public static final int Punto = 6;
  public static final int While = 12;
  public static final int Division = 22;
  public static final int Int = 4;
  public static final int Out = 40;
  public static final int Cadena = 8;
  public static final int Float = 5;
  public static final int Parentesis_c = 29;
  public static final int Publico = 16;
  public static final int Parentesis_a = 28;
  public static final int For = 13;
  public static final int EOF = 0;
  public static final int P_coma = 34;
  public static final int error = 1;
  public static final int Texto = 43;
  public static final int Linea = 2;
  public static final int Char = 7;
  public static final int Println = 41;
  public static final int D_puntos = 38;
  public static final int Op_atribucion = 25;
  public static final int Do = 11;
  public static final int Op_logico = 23;
  public static final int Identificador = 35;
  public static final int Resta = 20;
  public static final int Caracter = 37;
  public static final int Multiplicacion = 21;
  public static final int system = 39;
  public static final int Op_incremento = 26;
  public static final int Numero = 36;
  public static final int Suma = 19;
  public static final int Main = 14;
  public static final int Igual = 18;
  public static final int Comillas = 3;
}

